// Code generated by http://github.com/gojuno/minimock (v3.4.3). DO NOT EDIT.

package messages

//go:generate minimock -i github.com/Muvi7z/telegramBot.git/internal/model/messages.MessageSender -o message_sender_mock_test.go -n MessageSenderMock -p messages

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// MessageSenderMock implements MessageSender
type MessageSenderMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcSendMessage          func(userID int64, text string, buttons ...map[string]string) (err error)
	funcSendMessageOrigin    string
	inspectFuncSendMessage   func(userID int64, text string, buttons ...map[string]string)
	afterSendMessageCounter  uint64
	beforeSendMessageCounter uint64
	SendMessageMock          mMessageSenderMockSendMessage
}

// NewMessageSenderMock returns a mock for MessageSender
func NewMessageSenderMock(t minimock.Tester) *MessageSenderMock {
	m := &MessageSenderMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SendMessageMock = mMessageSenderMockSendMessage{mock: m}
	m.SendMessageMock.callArgs = []*MessageSenderMockSendMessageParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mMessageSenderMockSendMessage struct {
	optional           bool
	mock               *MessageSenderMock
	defaultExpectation *MessageSenderMockSendMessageExpectation
	expectations       []*MessageSenderMockSendMessageExpectation

	callArgs []*MessageSenderMockSendMessageParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// MessageSenderMockSendMessageExpectation specifies expectation struct of the MessageSender.SendMessage
type MessageSenderMockSendMessageExpectation struct {
	mock               *MessageSenderMock
	params             *MessageSenderMockSendMessageParams
	paramPtrs          *MessageSenderMockSendMessageParamPtrs
	expectationOrigins MessageSenderMockSendMessageExpectationOrigins
	results            *MessageSenderMockSendMessageResults
	returnOrigin       string
	Counter            uint64
}

// MessageSenderMockSendMessageParams contains parameters of the MessageSender.SendMessage
type MessageSenderMockSendMessageParams struct {
	userID  int64
	text    string
	buttons []map[string]string
}

// MessageSenderMockSendMessageParamPtrs contains pointers to parameters of the MessageSender.SendMessage
type MessageSenderMockSendMessageParamPtrs struct {
	userID  *int64
	text    *string
	buttons *[]map[string]string
}

// MessageSenderMockSendMessageResults contains results of the MessageSender.SendMessage
type MessageSenderMockSendMessageResults struct {
	err error
}

// MessageSenderMockSendMessageOrigins contains origins of expectations of the MessageSender.SendMessage
type MessageSenderMockSendMessageExpectationOrigins struct {
	origin        string
	originUserID  string
	originText    string
	originButtons string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmSendMessage *mMessageSenderMockSendMessage) Optional() *mMessageSenderMockSendMessage {
	mmSendMessage.optional = true
	return mmSendMessage
}

// Expect sets up expected params for MessageSender.SendMessage
func (mmSendMessage *mMessageSenderMockSendMessage) Expect(userID int64, text string, buttons ...map[string]string) *mMessageSenderMockSendMessage {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("MessageSenderMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &MessageSenderMockSendMessageExpectation{}
	}

	if mmSendMessage.defaultExpectation.paramPtrs != nil {
		mmSendMessage.mock.t.Fatalf("MessageSenderMock.SendMessage mock is already set by ExpectParams functions")
	}

	mmSendMessage.defaultExpectation.params = &MessageSenderMockSendMessageParams{userID, text, buttons}
	mmSendMessage.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmSendMessage.expectations {
		if minimock.Equal(e.params, mmSendMessage.defaultExpectation.params) {
			mmSendMessage.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSendMessage.defaultExpectation.params)
		}
	}

	return mmSendMessage
}

// ExpectUserIDParam1 sets up expected param userID for MessageSender.SendMessage
func (mmSendMessage *mMessageSenderMockSendMessage) ExpectUserIDParam1(userID int64) *mMessageSenderMockSendMessage {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("MessageSenderMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &MessageSenderMockSendMessageExpectation{}
	}

	if mmSendMessage.defaultExpectation.params != nil {
		mmSendMessage.mock.t.Fatalf("MessageSenderMock.SendMessage mock is already set by Expect")
	}

	if mmSendMessage.defaultExpectation.paramPtrs == nil {
		mmSendMessage.defaultExpectation.paramPtrs = &MessageSenderMockSendMessageParamPtrs{}
	}
	mmSendMessage.defaultExpectation.paramPtrs.userID = &userID
	mmSendMessage.defaultExpectation.expectationOrigins.originUserID = minimock.CallerInfo(1)

	return mmSendMessage
}

// ExpectTextParam2 sets up expected param text for MessageSender.SendMessage
func (mmSendMessage *mMessageSenderMockSendMessage) ExpectTextParam2(text string) *mMessageSenderMockSendMessage {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("MessageSenderMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &MessageSenderMockSendMessageExpectation{}
	}

	if mmSendMessage.defaultExpectation.params != nil {
		mmSendMessage.mock.t.Fatalf("MessageSenderMock.SendMessage mock is already set by Expect")
	}

	if mmSendMessage.defaultExpectation.paramPtrs == nil {
		mmSendMessage.defaultExpectation.paramPtrs = &MessageSenderMockSendMessageParamPtrs{}
	}
	mmSendMessage.defaultExpectation.paramPtrs.text = &text
	mmSendMessage.defaultExpectation.expectationOrigins.originText = minimock.CallerInfo(1)

	return mmSendMessage
}

// ExpectButtonsParam3 sets up expected param buttons for MessageSender.SendMessage
func (mmSendMessage *mMessageSenderMockSendMessage) ExpectButtonsParam3(buttons ...map[string]string) *mMessageSenderMockSendMessage {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("MessageSenderMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &MessageSenderMockSendMessageExpectation{}
	}

	if mmSendMessage.defaultExpectation.params != nil {
		mmSendMessage.mock.t.Fatalf("MessageSenderMock.SendMessage mock is already set by Expect")
	}

	if mmSendMessage.defaultExpectation.paramPtrs == nil {
		mmSendMessage.defaultExpectation.paramPtrs = &MessageSenderMockSendMessageParamPtrs{}
	}
	mmSendMessage.defaultExpectation.paramPtrs.buttons = &buttons
	mmSendMessage.defaultExpectation.expectationOrigins.originButtons = minimock.CallerInfo(1)

	return mmSendMessage
}

// Inspect accepts an inspector function that has same arguments as the MessageSender.SendMessage
func (mmSendMessage *mMessageSenderMockSendMessage) Inspect(f func(userID int64, text string, buttons ...map[string]string)) *mMessageSenderMockSendMessage {
	if mmSendMessage.mock.inspectFuncSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("Inspect function is already set for MessageSenderMock.SendMessage")
	}

	mmSendMessage.mock.inspectFuncSendMessage = f

	return mmSendMessage
}

// Return sets up results that will be returned by MessageSender.SendMessage
func (mmSendMessage *mMessageSenderMockSendMessage) Return(err error) *MessageSenderMock {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("MessageSenderMock.SendMessage mock is already set by Set")
	}

	if mmSendMessage.defaultExpectation == nil {
		mmSendMessage.defaultExpectation = &MessageSenderMockSendMessageExpectation{mock: mmSendMessage.mock}
	}
	mmSendMessage.defaultExpectation.results = &MessageSenderMockSendMessageResults{err}
	mmSendMessage.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmSendMessage.mock
}

// Set uses given function f to mock the MessageSender.SendMessage method
func (mmSendMessage *mMessageSenderMockSendMessage) Set(f func(userID int64, text string, buttons ...map[string]string) (err error)) *MessageSenderMock {
	if mmSendMessage.defaultExpectation != nil {
		mmSendMessage.mock.t.Fatalf("Default expectation is already set for the MessageSender.SendMessage method")
	}

	if len(mmSendMessage.expectations) > 0 {
		mmSendMessage.mock.t.Fatalf("Some expectations are already set for the MessageSender.SendMessage method")
	}

	mmSendMessage.mock.funcSendMessage = f
	mmSendMessage.mock.funcSendMessageOrigin = minimock.CallerInfo(1)
	return mmSendMessage.mock
}

// When sets expectation for the MessageSender.SendMessage which will trigger the result defined by the following
// Then helper
func (mmSendMessage *mMessageSenderMockSendMessage) When(userID int64, text string, buttons ...map[string]string) *MessageSenderMockSendMessageExpectation {
	if mmSendMessage.mock.funcSendMessage != nil {
		mmSendMessage.mock.t.Fatalf("MessageSenderMock.SendMessage mock is already set by Set")
	}

	expectation := &MessageSenderMockSendMessageExpectation{
		mock:               mmSendMessage.mock,
		params:             &MessageSenderMockSendMessageParams{userID, text, buttons},
		expectationOrigins: MessageSenderMockSendMessageExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmSendMessage.expectations = append(mmSendMessage.expectations, expectation)
	return expectation
}

// Then sets up MessageSender.SendMessage return parameters for the expectation previously defined by the When method
func (e *MessageSenderMockSendMessageExpectation) Then(err error) *MessageSenderMock {
	e.results = &MessageSenderMockSendMessageResults{err}
	return e.mock
}

// Times sets number of times MessageSender.SendMessage should be invoked
func (mmSendMessage *mMessageSenderMockSendMessage) Times(n uint64) *mMessageSenderMockSendMessage {
	if n == 0 {
		mmSendMessage.mock.t.Fatalf("Times of MessageSenderMock.SendMessage mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmSendMessage.expectedInvocations, n)
	mmSendMessage.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmSendMessage
}

func (mmSendMessage *mMessageSenderMockSendMessage) invocationsDone() bool {
	if len(mmSendMessage.expectations) == 0 && mmSendMessage.defaultExpectation == nil && mmSendMessage.mock.funcSendMessage == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmSendMessage.mock.afterSendMessageCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmSendMessage.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// SendMessage implements MessageSender
func (mmSendMessage *MessageSenderMock) SendMessage(userID int64, text string, buttons ...map[string]string) (err error) {
	mm_atomic.AddUint64(&mmSendMessage.beforeSendMessageCounter, 1)
	defer mm_atomic.AddUint64(&mmSendMessage.afterSendMessageCounter, 1)

	mmSendMessage.t.Helper()

	if mmSendMessage.inspectFuncSendMessage != nil {
		mmSendMessage.inspectFuncSendMessage(userID, text, buttons...)
	}

	mm_params := MessageSenderMockSendMessageParams{userID, text, buttons}

	// Record call args
	mmSendMessage.SendMessageMock.mutex.Lock()
	mmSendMessage.SendMessageMock.callArgs = append(mmSendMessage.SendMessageMock.callArgs, &mm_params)
	mmSendMessage.SendMessageMock.mutex.Unlock()

	for _, e := range mmSendMessage.SendMessageMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmSendMessage.SendMessageMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSendMessage.SendMessageMock.defaultExpectation.Counter, 1)
		mm_want := mmSendMessage.SendMessageMock.defaultExpectation.params
		mm_want_ptrs := mmSendMessage.SendMessageMock.defaultExpectation.paramPtrs

		mm_got := MessageSenderMockSendMessageParams{userID, text, buttons}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userID != nil && !minimock.Equal(*mm_want_ptrs.userID, mm_got.userID) {
				mmSendMessage.t.Errorf("MessageSenderMock.SendMessage got unexpected parameter userID, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendMessage.SendMessageMock.defaultExpectation.expectationOrigins.originUserID, *mm_want_ptrs.userID, mm_got.userID, minimock.Diff(*mm_want_ptrs.userID, mm_got.userID))
			}

			if mm_want_ptrs.text != nil && !minimock.Equal(*mm_want_ptrs.text, mm_got.text) {
				mmSendMessage.t.Errorf("MessageSenderMock.SendMessage got unexpected parameter text, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendMessage.SendMessageMock.defaultExpectation.expectationOrigins.originText, *mm_want_ptrs.text, mm_got.text, minimock.Diff(*mm_want_ptrs.text, mm_got.text))
			}

			if mm_want_ptrs.buttons != nil && !minimock.Equal(*mm_want_ptrs.buttons, mm_got.buttons) {
				mmSendMessage.t.Errorf("MessageSenderMock.SendMessage got unexpected parameter buttons, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmSendMessage.SendMessageMock.defaultExpectation.expectationOrigins.originButtons, *mm_want_ptrs.buttons, mm_got.buttons, minimock.Diff(*mm_want_ptrs.buttons, mm_got.buttons))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSendMessage.t.Errorf("MessageSenderMock.SendMessage got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmSendMessage.SendMessageMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSendMessage.SendMessageMock.defaultExpectation.results
		if mm_results == nil {
			mmSendMessage.t.Fatal("No results are set for the MessageSenderMock.SendMessage")
		}
		return (*mm_results).err
	}
	if mmSendMessage.funcSendMessage != nil {
		return mmSendMessage.funcSendMessage(userID, text, buttons...)
	}
	mmSendMessage.t.Fatalf("Unexpected call to MessageSenderMock.SendMessage. %v %v %v", userID, text, buttons)
	return
}

// SendMessageAfterCounter returns a count of finished MessageSenderMock.SendMessage invocations
func (mmSendMessage *MessageSenderMock) SendMessageAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendMessage.afterSendMessageCounter)
}

// SendMessageBeforeCounter returns a count of MessageSenderMock.SendMessage invocations
func (mmSendMessage *MessageSenderMock) SendMessageBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSendMessage.beforeSendMessageCounter)
}

// Calls returns a list of arguments used in each call to MessageSenderMock.SendMessage.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSendMessage *mMessageSenderMockSendMessage) Calls() []*MessageSenderMockSendMessageParams {
	mmSendMessage.mutex.RLock()

	argCopy := make([]*MessageSenderMockSendMessageParams, len(mmSendMessage.callArgs))
	copy(argCopy, mmSendMessage.callArgs)

	mmSendMessage.mutex.RUnlock()

	return argCopy
}

// MinimockSendMessageDone returns true if the count of the SendMessage invocations corresponds
// the number of defined expectations
func (m *MessageSenderMock) MinimockSendMessageDone() bool {
	if m.SendMessageMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.SendMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.SendMessageMock.invocationsDone()
}

// MinimockSendMessageInspect logs each unmet expectation
func (m *MessageSenderMock) MinimockSendMessageInspect() {
	for _, e := range m.SendMessageMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to MessageSenderMock.SendMessage at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterSendMessageCounter := mm_atomic.LoadUint64(&m.afterSendMessageCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.SendMessageMock.defaultExpectation != nil && afterSendMessageCounter < 1 {
		if m.SendMessageMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to MessageSenderMock.SendMessage at\n%s", m.SendMessageMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to MessageSenderMock.SendMessage at\n%s with params: %#v", m.SendMessageMock.defaultExpectation.expectationOrigins.origin, *m.SendMessageMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSendMessage != nil && afterSendMessageCounter < 1 {
		m.t.Errorf("Expected call to MessageSenderMock.SendMessage at\n%s", m.funcSendMessageOrigin)
	}

	if !m.SendMessageMock.invocationsDone() && afterSendMessageCounter > 0 {
		m.t.Errorf("Expected %d calls to MessageSenderMock.SendMessage at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.SendMessageMock.expectedInvocations), m.SendMessageMock.expectedInvocationsOrigin, afterSendMessageCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *MessageSenderMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockSendMessageInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *MessageSenderMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *MessageSenderMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSendMessageDone()
}
